default:
	cd cola_output && make && cd ..
	cd cola_output_512grid && make && cd ..
	cd cola_output_nstep20 && make && cd ..
	cd cola_output_nstep5 && make && cd ..
	cd cola_output_512par && make && cd ..
	cd cola_output_nstep40 && make && cd ..
	cd cola_output_nstep60 && make && cd ..
	cd cola_output_nstep80 && make && cd ..
	cd cola_output_nstep1000 && make && cd ..
	cd cola_output_128box_1024c && make && cd ..
	cd cola_output_128box_800c && make && cd ..
clean:
	cd cola_output && make clean && cd ..
	cd cola_output_512grid && make clean && cd ..
	cd cola_output_nstep20 && make clean && cd ..
	cd cola_output_nstep5 && make clean && cd ..
	cd cola_output_512par && make clean && cd ..
	cd cola_output_nstep40 && make clean && cd ..
	cd cola_output_nstep60 && make clean && cd ..
	cd cola_output_nstep80 && make clean && cd ..
	cd cola_output_nstep1000 && make clean && cd ..
	cd cola_output_128box_1024c && make clean && cd ..
	cd cola_output_128box_800c && make clean && cd ..
cleanall:
	cd cola_output && make cleanall && cd ..
	cd cola_output_512grid && make cleanall && cd ..
	cd cola_output_nstep20 && make cleanall && cd ..
	cd cola_output_nstep5 && make cleanall && cd ..
	cd cola_output_512par && make cleanall && cd ..
	cd cola_output_nstep40 && make cleanall && cd ..
	cd cola_output_nstep60 && make cleanall && cd ..
	cd cola_output_nstep80 && make cleanall && cd ..
	cd cola_output_nstep1000 && make cleanall && cd ..
	cd cola_output_128box_1024c && make cleanall && cd ..
	cd cola_output_128box_800c && make cleanall && cd ..
